### ISSUE TITLE
header numbering in markdown should be organizational, not stylistic

### ISSUE THREAD

**Issue by deargle** [bdjulian/bdjulian.github.io#5]
I wrestle with this too, but I think the right way is to use l2 when it's a l2, l3 when it's actually a l3, etc. If a header looks too big, you can change how it looks by tinkering with the stylesheet. I can show you that later. But for now, I'd make the header numbering (number of `#` signs) match the word doc level heading.

**Comment by deargle** [comment]
e.g., 
![image](https://user-images.githubusercontent.com/1174653/104641121-99af7d80-5666-11eb-9699-6da1e684c818.png)

**Comment by deargle** [comment]
^^ is an example where it skips around, but shouldn't. The one exception is page title. You could leave that as a l1, and then have the first major section _also_ be a l1, and then later you can go back and add styling to the title to make it bigger and more page-title-ish. But `Section 1` in the screenshot above would be a l1.

**Comment by deargle** [comment]
Eh, no one does this in practice, forget it.

**Comment by bdjulian** [comment]
Well shoot
