### ISSUE TITLE
General issues in a-study-guide.md

### ISSUE THREAD

**Issue by deargle** [bdjulian/bdjulian.github.io#7]
One part of the manuscript says:

   > While reading, identify main concepts of botnet detection and the botnet detection industry that would affect a company or business and their ability to safely protect their assets (a security mindset).

This section was offputting, no other part of the guide suggests that the reader do something. Some possible fixes:

* put directives on their own lines, and wrap them in different style presentation
* remove all directives?

I dunno

**Comment by bdjulian** [comment]
Okay, you're right. It uses language not present in the rest of the paper. I'll try and change the language.
